DATASETS:
  IMAGE_DIR_PATH: "HierText"
  ANN_DIR_PATH: "HierText/gt"
  BATCH_SIZE: 2
  NUMWORKS: 0
MODEL:
  NUM_OBJECT_QUERIES: 100

INPUT:
  CROP:
    SIZE: [224, 320, 480, 512] # [640, 800, 960, 1120]
    MAX_SIZE: 512
